<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE program [
<!ELEMENT program (taci+)>
<!ELEMENT taci (dst?,src1?,src2?)>
<!ELEMENT dst (CDATA)>
<!ELEMENT src1 (CDATA)>
<!ELEMENT src2 (CDATA)>
<!ATTLIST program name CDATA #IMPLIED>
<!ATTLIST taci opcode CDATA #REQUIRED>
<!ATTLIST dst kind (literal|variable) "variable">
<!ATTLIST dst type (integer|string) "integer">
<!ATTLIST src1 kind (literal|variable) "variable">
<!ATTLIST src1 type (integer|string) "integer">
<!ATTLIST src2 kind (literal|variable) "variable">
<!ATTLIST src2 type (integer|string) "integer">
<!ENTITY language "Three-Address Code Interpreter">
]>
<program name="Testing opcodes">
  <taci opcode="MOV">
    <dst>a</dst>
    <src1 kind="literal">20</src1>
  </taci>
  <taci opcode="PRINT">
    <src1 kind="literal" type="string">a = </src1>
  </taci>   
  <taci opcode="PRINTLN">
    <src1>a</src1>
  </taci>
  <taci opcode="STRINT">
    <dst>int_a</dst>
    <src1>a</src1>
  </taci>
  <taci opcode="PRINTLN">
    <src1 kind="literal" type="string">String a to Integer int_a</src1>
  </taci>   
  <taci opcode="PRINT">
    <src1 kind="literal" type="string">int_a = </src1>
  </taci>   
  <taci opcode="PRINTLN">
    <src1>int_a</src1>
  </taci>
  <taci opcode="MOV">
    <dst>b</dst>
    <src1 kind="literal">200</src1>
  </taci>
  <taci opcode="PRINT">
    <src1 kind="literal" type="string">b = </src1>
  </taci>   
  <taci opcode="PRINTLN">
    <src1>b</src1>
  </taci>
  <taci opcode="ADD">
    <dst>a+a</dst>
    <src1>a</src1>
    <src2>int_a</src2>
  </taci>
  <taci opcode="PRINT">
    <src1 kind="literal" type="string">a + int_a = </src1>
  </taci>   
  <taci opcode="PRINTLN">
    <src1>a+a</src1>
  </taci>
  <taci opcode="ADD">
    <dst>b</dst>
    <src1>b</src1>
    <src2 kind="literal">2</src2>
  </taci>
  <taci opcode="PRINT">
    <src1 kind="literal" type="string">b + 2 = </src1>
  </taci>   
  <taci opcode="PRINTLN">
    <src1>b</src1>
  </taci>
  <taci opcode="INTSTR">
    <dst>a</dst>
    <src1>a</src1>
  </taci>
  <taci opcode="PRINTLN">
    <src1 kind="literal" type="string">Integer a to String a</src1>
  </taci>   
  <taci opcode="CONCAT">
    <dst>aa</dst>
    <src1>a</src1>
    <src2>a</src2>
  </taci>
  <taci opcode="PRINT">
    <src1 kind="literal" type="string">Concat aa = </src1>
  </taci>   
  <taci opcode="PRINTLN">
    <src1>aa</src1>
  </taci>
  <taci opcode="STRINT">
    <dst>aa</dst>
    <src1>aa</src1>
  </taci>
  <taci opcode="PRINTLN">
    <src1 kind="literal" type="string">String aa to Integer aa</src1>
  </taci>   
  <taci opcode="ADD">
    <dst>aa</dst>
    <src1>aa</src1>
    <src2 >b</src2>
  </taci>
  <taci opcode="PRINT">
    <src1 kind="literal" type="string">aa + b = </src1>
  </taci>   
  <taci opcode="PRINTLN">
    <src1>aa</src1>
  </taci>
</program> 